language: node_js
env:
  global:
    - SQRL_TEST_REDIS=localhost:6379
node_js:
  - 'node'
  - '8'
  - '10'
services:
  - redis-server
script:
  - npm run coverage # jest test with coverage flag does coverage too
  - npm run test:integration
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
